### ISSUE TITLE
Random number seed is always the same on the simulator

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/micropython-microbit-v2-simulator#85]
This does't match the device and is unhelpful when teaching random numbers.

https://stackoverflow.com/questions/74077710/microbit-python-random-library-only-generates-one-number

**Comment by microbit-matt-hillsdon** [comment]
We need to implement this stub: 
https://github.com/microbit-foundation/micropython-microbit-v2-simulator/blob/b88271f625e9ad1158954b2b00a4542eba0195a8/src/microbithal_js.c#L392

Despite the comment, it's only used for the seed in the port config. 

We dug into this a bit, and despite CODAL having a random number generator, MicroPython uses its own seeded from CODAL's one (potentially reseeded by the user).

**Comment by microbit-carlos** [comment]
Looks like we had a case of:
![xkcd random](https://imgs.xkcd.com/comics/random_number.png)
https://xkcd.com/221/

**Comment by microbit-matt-hillsdon** [comment]
I looked into the other comments from the StackOverflow question:

#### random.seed doesn't work in the simulator

This seems to work for me, please raise a new issue with an example program if you can reproduce. For the moment, until we fix this issue, the default seed is zero to setting it to that won't affect anything.
    
#### machine.reset seems to freeze on the emulator. Will be updating with solution after I test with microbits

This doesn't reproduce straightforwardly, however trying variations on the program on stackoverflow, I raised https://github.com/microbit-foundation/micropython-microbit-v2-simulator/issues/86

**Comment by microbit-matt-hillsdon** [comment]
The random seed issue is fixed by #87. 

For this change to be available in the Python Editor V3 we still need to release the simulator. I'll do this once we've had a chance to look at the related issue #86.

**Comment by microbit-matt-hillsdon** [comment]
This change is now live in the V3 Python Editor as part of simulator [0.1.6](https://github.com/microbit-foundation/micropython-microbit-v2-simulator/releases/tag/v0.1.6).
