### ISSUE TITLE
Cannot stop simulator with program containing reset in tight loop

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/micropython-microbit-v2-simulator#86]
```
from microbit import *
import machine
import random

while True:
    num = random.randint(1, 7)
    display.show(num)
    sleep(10) # works ok for me with 20ms
    machine.reset()
```

It stops OK with 20ms of delay or if you remove machine.reset().

**Comment by microbit-carlos** [comment]
It likely does the same thing under the hood, but just to confirm that replacing `machine.reset` with `reset` ( from the `microbit` module), has the same result.

**Comment by microbit-matt-hillsdon** [comment]
The minimal repo just calls reset. The loop never executes more than once per run anyway.

**Comment by microbit-matt-hillsdon** [comment]
I think it could be that you're very likely to be trying to stop the simulator when it's in the process of resetting. 

We need to handle the case where the program stopped because of a reset but the user has requested a stop, rather than just assuming that the program stopping with ResetError means we should reset.

**Comment by microbit-matt-hillsdon** [comment]
There's an equivalent but less serious scenario where the program could end with a panic and would display that panic even if the user had attempted to stop it.

**Comment by microbit-matt-hillsdon** [comment]
Possible interleavings:

1. Program starts
2. You send stop which sets a flag
3. Program stops because of flag

Everything's awesome

1. Program starts
2. You send stop which sets a flag
3. Program stops on its own, potentially requesting a restart

We need to notice the flag and not request the restart (or perhaps collapse with the next case).

1. Program starts
2. Program stops on its own, requesting restart, job queued to do so
3. You send stop which sets a flag
4. Job to restart runs

We need to know to ignore or cancel this planned restart.

**Comment by microbit-matt-hillsdon** [comment]
This is now in 0.1.6 of the simulator. I'll update the version used in the V3 editor late this evening or tomorrow morning.

**Comment by microbit-matt-hillsdon** [comment]
Now live in the V3 editor.

**Comment by microbit-matt-hillsdon** [comment]
Reopening as this has been reverted due to #90. I think we can largely reinstate it but the `await stop` calls need a different approach.

**Comment by microbit-matt-hillsdon** [comment]
Test program from #90 for convenience:


```python
from microbit import *
import random

r = random.randrange(0, 100)
while True:
    print(r)
    sleep(1000)
```

**Comment by microbit-matt-hillsdon** [comment]
Fix merged but needs a release before it will be live (again) on the V3 editor.

**Comment by microbit-matt-hillsdon** [comment]
New fix now live.
